remote:
  inference-web:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: hiv-orderly.dide.ic.ac.uk
      port: 443
      prefix: inference-data
      token: $ORDERLYWEB_GITHUB_TOKEN
    # primary: true
    default_branch: main
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/kp-data
  fertility:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility
  naomi_2021:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-orderly-naomi2
  malawi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/mwi-hiv-orderly

global_resources:
  global
  
fields:
  requester:
    required: false
  author:
    required: false

vault:
  addr: https://vault.dide.ic.ac.uk:8200

tags:
  surveillance_only
